[tool.poetry]
name = "biliapi"
version = "0.1.0"
description = ""
authors = ["aoout <wuz66280@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
